Tracer documentation
lambdaclass/era_vm pull request #100
Opened 2024-07-24 21:38 UTC by gianbelinche

2024-07-24 22:14 UTC, Oppen commented on docs/general.md
> +An important Tracer is what whe call the `PrintTracer`, with it we can print stuff on solidity contracts.
```suggestion
An important Tracer is what we call the `PrintTracer`, with it we can print stuff on solidity contracts.
```

2024-07-24 22:15 UTC, Oppen commented on docs/general.md
> +Right know that is the only function the trait has, in the future more may be added as needed, like `before_decoding`, `after_decoding` or `after_execution`
```suggestion
Right now that is the only function the trait has, in the future more may be added as needed, like `before_decoding`, `after_decoding` or `after_execution`
```

2024-07-24 22:16 UTC, Oppen commented on docs/general.md
> +Here is were the PrintTracer does its magic, before every execution it looks if the opcode executed is a `HeapWrite`, this is the opcode responsible for storing thing in the Heap, which is in the end
```suggestion
Here is where the PrintTracer does its magic, before every execution it looks if the opcode executed is a `HeapWrite`, this is the opcode responsible for storing things in the Heap, which is in the end what we are doing with the `mstore`, if the value being written is the magic value and its being written on the debug slot, then we know we are in one of the print functions and we need to print the value.
```

2024-07-25 19:04 UTC, juan518munoz requested changes
The print tracer example looks great! But I would complete the example by telling which parts of our codebase (besides solidity) we need to change to make it work.

2024-07-25 19:37 UTC, Oppen approved these changes

2024-07-25 20:54 UTC, juan518munoz approved these changes
Excellent!

2024-07-25 21:20 UTC, merged