Fix solidity/ethereum/inlineAssembly
lambdaclass/era_vm pull request #164
Opened 2024-08-06 20:52 UTC by MarcosNicolau

They were failing because we were not properly storing the values in the transient storage between frames. Also, in the `fat_pointer_read` opcode we were incorrectly reading the values.

2024-08-06 21:38 UTC, Oppen approved these changes

2024-08-07 15:37 UTC, fkrause98 requested changes
Great job! Let's discuss some changes and we're done here.

2024-08-07 15:37 UTC, fkrause98 commented on src/op_handlers/ret.rs
> +fn save_transient_store(vm: &mut VMState, prev_storage: InMemory) {
Let's make this return a `Result<(), EraVMError>`, also rewrite these unwraps to proper error handling or use `?`,.

2024-08-07 15:51 UTC, JulianVentura approved these changes
LGTM

2024-08-07 15:52 UTC, fkrause98 approved these changes

2024-08-07 16:28 UTC, merged