add precompiles explanation
lambdaclass/era_vm pull request #180
Opened 2024-08-09 14:22 UTC by jorbush

#### Precompiles
- [ ] what are precompiles?
- [ ] how calls to precompiles work
- [ ] use keccak as an example as it's used on every deployment (it goes to the `keccak.yul` contract which then uses the `precompile` opcode)
#### System Calls
- [ ] What are system contracts?
- [ ] What's a system call?
- [ ] Show some examples (deployer, nonce holder, L2BaseToken) and what they're used for.

2024-08-12 14:06 UTC, MarcosNicolau requested changes

2024-08-12 14:06 UTC, MarcosNicolau commented on docs/general.md
> +2. **Execution in `keccak.yul`**: The `keccak256_rounds_function` handles the precompile's logic. It processes the input data in blocks, applies the keccak hash algorithm, and then stores the result
I would add that the intermediate state of the hash gets stored and not the finalize digest.

2024-08-12 14:12 UTC, juan518munoz commented on docs/general.md
> +    ```
`LogQuery` was removed from the precompiles impl.

2024-08-12 18:54 UTC, MarcosNicolau approved these changes
LGTM 👍

2024-08-13 13:08 UTC, gianbelinche requested changes

2024-08-13 13:08 UTC, gianbelinche commented on docs/general.md
> +2. **Execution in `keccak.yul`**: The `keccak256_rounds_function` processes the input data in blocks, applies the _Keccak hash algorithm_, and stores the intermediate hash state in the contract's mem
I think it is not sufficiently clear that when someone needs to execute a precompile it calls a certain system contract, and that is the one that executes the opcode, in this case keccak.yul is the one executing the precompile opcode

2024-08-13 13:42 UTC, gianbelinche approved these changes

2024-08-13 14:01 UTC, merged