Make `Rollbackable` fields private
lambdaclass/era_vm pull request #209
Opened 2024-08-20 18:09 UTC by juan518munoz

2024-08-28 16:03 UTC, fkrause98 approved these changes

2024-08-28 17:01 UTC, juan518munoz commented on src/rollbacks.rs
> +    pub fn inner_ref(&self) -> &HashMap<K, V> {
We use it to get `storage` and `transient_storage` changes, see [here](https://github.com/lambdaclass/era_vm/blob/b44437328926f92e772c4d9527750332a5d2397c/src/state.rs#L88-L94).

2024-08-29 16:00 UTC, fkrause98 approved these changes

2024-08-29 16:01 UTC, fkrause98 commented
> @fkrause98 latest merge from `main` made most comments on this PR outdated, do you consider any of them still relevant?
> 
> Also, be sure to check [the PR](https://github.com/lambdaclass/zksync-era/pull/247) opened in zksync-era adapting to this changes whenever you have time to.

Let's ignore the comments I've left then.

2024-09-04 20:45 UTC, MarcosNicolau requested changes

2024-09-04 20:45 UTC, MarcosNicolau commented on src/state.rs
> +            .inner_ref()
we could remove this `inner_ref` and use `get` directly.

2024-09-04 21:01 UTC, MarcosNicolau approved these changes

2024-09-04 22:26 UTC, Oppen approved these changes

2024-09-05 19:03 UTC, fkrause98 approved these changes

2024-09-05 19:44 UTC, merged