Fix Deployer
lambdaclass/era_vm pull request #91
Opened 2024-07-23 21:26 UTC by gianbelinche

This PR fixes tests without `--disable-deployer` flag.

In order to do it, when a near call returns, It now restores the stack of the previous frame as It was when the call was made, instead of replacing it with the changes performed on the nearcall.

This does not comply with whats said on the primer 
_All near calls inside the contract are sharing the same memory space (heap, stack), and do not roll back the changes to this memory if they fail_

However the formal specification does not say anything about this.

2024-07-23 21:48 UTC, juan518munoz approved these changes

2024-07-24 14:59 UTC, jorbush approved these changes
LGTM! Even you have fixed the resizing case for stack

2024-07-24 15:12 UTC, juan518munoz requested changes

2024-07-24 15:12 UTC, juan518munoz commented on Makefile
>  test:
Running from a clean `clone` (`git clean -xdf`):
```bash
➜  era_vm git:(fix-deployer) ✗ make test
export LLVM_SYS_170_PREFIX=/Users/jm-lambda/Coding/zk/era_vm/era-compiler-tester/target-llvm/target-final/ && cd era-compiler-tester && cargo run --verbose --features lambda_vm --release --bin compiler-tester -- --path  tests/solidity/simple/yul_instructions/ --target EraVM --mode='Y+M3B3 0.8.26'
/bin/sh: line 0: cd: era-compiler-tester: No such file or directory
make: *** [test] Error 1
```

We should add `deps` as a `test` make dependency:
```Makefile
test: deps
```

2024-07-24 16:11 UTC, juan518munoz approved these changes

2024-07-24 17:37 UTC, merged